cosbench-driver:
    image: joyent/cosbench-manta
    restart: always
    mem_limit: 2g
    environment:
        - MODE=driver
        - CONSUL_AGENT=1
        - JAVA_OPTS=-Xmx1500m
        - LISTENING_PORT=18088
    expose:
        - 18088

cosbench-controller:
    image: joyent/cosbench-manta
    restart: always
    mem_limit: 1g
    environment:
        - MODE=controller
        - CONSUL_AGENT=1
        - JAVA_OPTS=-Xmx800m
        - LISTENING_PORT=19088
    ports:
        - 19088:19088

# Start with a single host which will bootstrap the cluster.
# In production we'll want to use an HA cluster.
consul:
    image: consul:v0.7.0
    restart: always
    mem_limit: 128m
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    ports:
      - 8500
    dns:
       - 127.0.0.1
    command: agent -server -client=0.0.0.0 -bootstrap -ui
